# Generated by Django 4.2.6 on 2023-10-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
