# Generated by Django 4.2.6 on 2023-10-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0012_delete_category_delete_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.IntegerField()),
                ('categoryname', models.CharField(max_length=100)),
                ('subcategoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_category', models.CharField(max_length=100)),
                ('job_subcategory', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=1000)),
                ('job_location', models.CharField(max_length=100)),
                ('job_experience', models.CharField(max_length=100)),
                ('job_salary', models.CharField(max_length=100)),
            ],
        ),
    ]
