# Generated by Django 4.2.6 on 2023-10-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_category', to='job.category'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_subcategory', to='job.category'),
        ),
    ]
