# Generated by Django 4.2.6 on 2023-10-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategoryname',
        ),
    ]
