# Generated by Django 4.2.6 on 2023-11-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_alter_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
    ]
