# Generated by Django 4.2.6 on 2023-11-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_alter_jobapplication_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='user',
            new_name='jobs',
        ),
    ]
