# Generated by Django 4.2.6 on 2023-11-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_rename_user_jobapplication_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='jobs',
            new_name='user',
        ),
    ]
