# Generated by Django 4.2.6 on 2023-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_alter_jobs_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.CharField(max_length=1000),
        ),
    ]
