# Generated by Django 4.2.6 on 2023-11-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_remove_jobapplication_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job',
            new_name='user',
        ),
    ]
