# Generated by Django 4.2.6 on 2023-11-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_rename_job_jobapplication_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='user',
            new_name='job',
        ),
    ]
