# Generated by Django 4.2.6 on 2023-11-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_alter_jobs_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_category', to='job.category'),
        ),
    ]
