# Generated by Django 4.2.6 on 2023-11-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0048_remove_jobapplication_user_jobapplication_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
    ]
