# Generated by Django 4.2.6 on 2023-11-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0050_jobapplication_jo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='jo',
            new_name='job',
        ),
    ]
