# Generated by Django 4.2.6 on 2023-11-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0051_rename_jo_jobapplication_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
