# Generated by Django 4.2.6 on 2023-11-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0054_category_categoryid_alter_jobs_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(null=True, upload_to='cv_uploads/'),
        ),
    ]
