# Generated by Django 4.2.6 on 2023-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0059_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='cv_uploads/'),
        ),
    ]
